USE [ebidtw]
GO
/****** Object:  Table [dbo].[SYS_USERS]    Script Date: 03/22/2017 16:58:35 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SYS_USERS](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[USER_ACCOUNT] [nvarchar](100) NULL,
	[USER_PWD] [nvarchar](100) NULL,
	[EXPIRED_DATE] [datetime] NULL,
	[ACTIVED] [int] NULL,
	[RESERVED] [int] NULL,
	[USER_TYPE] [int] NULL,
	[DELETED] [int] NULL,
	[CREATE_DATE] [datetime] NULL,
	[CREATE_USER] [nvarchar](100) NULL,
	[UPDATE_DATE] [datetime] NULL,
	[UPDATE_USER] [nvarchar](100) NULL,
	[FULL_NAME] [nvarchar](100) NULL,
 CONSTRAINT [PK__SYS_USER__3214EC272818EA29] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY],
 CONSTRAINT [UQ__SYS_USER__3CA1C3112AF556D4] UNIQUE NONCLUSTERED 
(
	[USER_ACCOUNT] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[SYS_USERS] ON
INSERT [dbo].[SYS_USERS] ([ID], [USER_ACCOUNT], [USER_PWD], [EXPIRED_DATE], [ACTIVED], [RESERVED], [USER_TYPE], [DELETED], [CREATE_DATE], [CREATE_USER], [UPDATE_DATE], [UPDATE_USER], [FULL_NAME]) VALUES (1, N'admin01', N'XohImNooBHFR0OVvjcYpJ3NgPQ1qq73WKhHvch0VQtg=', NULL, 1, 0, NULL, 0, CAST(0x0000A68E00A8A4F2 AS DateTime), NULL, NULL, NULL, N'ADMIN')
INSERT [dbo].[SYS_USERS] ([ID], [USER_ACCOUNT], [USER_PWD], [EXPIRED_DATE], [ACTIVED], [RESERVED], [USER_TYPE], [DELETED], [CREATE_DATE], [CREATE_USER], [UPDATE_DATE], [UPDATE_USER], [FULL_NAME]) VALUES (2, N'F7970003', N'XohImNooBHFR0OVvjcYpJ3NgPQ1qq73WKhHvch0VQtg=', CAST(0x0000000000000000 AS DateTime), 1, 0, 3, 0, CAST(0x0000A68E00A8B861 AS DateTime), NULL, NULL, N'admin01', N'小肆實業')
INSERT [dbo].[SYS_USERS] ([ID], [USER_ACCOUNT], [USER_PWD], [EXPIRED_DATE], [ACTIVED], [RESERVED], [USER_TYPE], [DELETED], [CREATE_DATE], [CREATE_USER], [UPDATE_DATE], [UPDATE_USER], [FULL_NAME]) VALUES (3, N'2601917', N'XohImNooBHFR0OVvjcYpJ3NgPQ1qq73WKhHvch0VQtg=', NULL, 1, 0, NULL, 0, CAST(0x0000A68E00AA52C0 AS DateTime), NULL, NULL, NULL, N'聚能光電有限公司')
INSERT [dbo].[SYS_USERS] ([ID], [USER_ACCOUNT], [USER_PWD], [EXPIRED_DATE], [ACTIVED], [RESERVED], [USER_TYPE], [DELETED], [CREATE_DATE], [CREATE_USER], [UPDATE_DATE], [UPDATE_USER], [FULL_NAME]) VALUES (4, N'7970003', N'XohImNooBHFR0OVvjcYpJ3NgPQ1qq73WKhHvch0VQtg=', NULL, 1, 0, NULL, 0, CAST(0x0000A6EB00978950 AS DateTime), NULL, NULL, NULL, N'小董測試有限公司')
INSERT [dbo].[SYS_USERS] ([ID], [USER_ACCOUNT], [USER_PWD], [EXPIRED_DATE], [ACTIVED], [RESERVED], [USER_TYPE], [DELETED], [CREATE_DATE], [CREATE_USER], [UPDATE_DATE], [UPDATE_USER], [FULL_NAME]) VALUES (10, N'H2601917', N'XohImNooBHFR0OVvjcYpJ3NgPQ1qq73WKhHvch0VQtg=', NULL, 1, 0, NULL, 0, CAST(0x0000A6FF00A9383C AS DateTime), N'H2601917', CAST(0x0000A6FF00A9383C AS DateTime), N'H2601917', N'钜亿科技')
INSERT [dbo].[SYS_USERS] ([ID], [USER_ACCOUNT], [USER_PWD], [EXPIRED_DATE], [ACTIVED], [RESERVED], [USER_TYPE], [DELETED], [CREATE_DATE], [CREATE_USER], [UPDATE_DATE], [UPDATE_USER], [FULL_NAME]) VALUES (11, NULL, NULL, NULL, 1, 0, NULL, 0, CAST(0x0000A700011EBE63 AS DateTime), NULL, CAST(0x0000A700011EBE63 AS DateTime), NULL, N'聚能光電有限公司')
INSERT [dbo].[SYS_USERS] ([ID], [USER_ACCOUNT], [USER_PWD], [EXPIRED_DATE], [ACTIVED], [RESERVED], [USER_TYPE], [DELETED], [CREATE_DATE], [CREATE_USER], [UPDATE_DATE], [UPDATE_USER], [FULL_NAME]) VALUES (13, N'H26019171', N'XohImNooBHFR0OVvjcYpJ3NgPQ1qq73WKhHvch0VQtg=', NULL, 1, 0, NULL, 0, CAST(0x0000A70001364E1C AS DateTime), N'H26019171', CAST(0x0000A70001364E1C AS DateTime), N'H26019171', N'钜亿科技2')
INSERT [dbo].[SYS_USERS] ([ID], [USER_ACCOUNT], [USER_PWD], [EXPIRED_DATE], [ACTIVED], [RESERVED], [USER_TYPE], [DELETED], [CREATE_DATE], [CREATE_USER], [UPDATE_DATE], [UPDATE_USER], [FULL_NAME]) VALUES (15, N'', N'47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU=', NULL, 1, 0, NULL, 0, CAST(0x0000A71900A3F407 AS DateTime), N'', CAST(0x0000A71900A3F407 AS DateTime), N'', N'')
INSERT [dbo].[SYS_USERS] ([ID], [USER_ACCOUNT], [USER_PWD], [EXPIRED_DATE], [ACTIVED], [RESERVED], [USER_TYPE], [DELETED], [CREATE_DATE], [CREATE_USER], [UPDATE_DATE], [UPDATE_USER], [FULL_NAME]) VALUES (16, N'vendor_01', N'Vrhnli5Ms52SwzYjYM6f+dEffmURRJM+76BeDIqeUTY=', NULL, 1, 0, NULL, 0, CAST(0x0000A71900FB0502 AS DateTime), N'vendor_01', CAST(0x0000A71900FB0502 AS DateTime), N'vendor_01', N'捷达士')
INSERT [dbo].[SYS_USERS] ([ID], [USER_ACCOUNT], [USER_PWD], [EXPIRED_DATE], [ACTIVED], [RESERVED], [USER_TYPE], [DELETED], [CREATE_DATE], [CREATE_USER], [UPDATE_DATE], [UPDATE_USER], [FULL_NAME]) VALUES (20, N'vendor_02', N'Vrhnli5Ms52SwzYjYM6f+dEffmURRJM+76BeDIqeUTY=', NULL, 1, 0, NULL, 0, CAST(0x0000A71A008F080D AS DateTime), N'vendor_02', CAST(0x0000A71A008F080D AS DateTime), N'vendor_02', N'沃德科技有限公司')
INSERT [dbo].[SYS_USERS] ([ID], [USER_ACCOUNT], [USER_PWD], [EXPIRED_DATE], [ACTIVED], [RESERVED], [USER_TYPE], [DELETED], [CREATE_DATE], [CREATE_USER], [UPDATE_DATE], [UPDATE_USER], [FULL_NAME]) VALUES (21, N'vendor_03', N'Vrhnli5Ms52SwzYjYM6f+dEffmURRJM+76BeDIqeUTY=', NULL, 1, 0, NULL, 0, CAST(0x0000A71A00A79BCE AS DateTime), N'vendor_03', CAST(0x0000A71A00A79BCE AS DateTime), N'vendor_03', N'苏州福莱盈电子有限公司')
INSERT [dbo].[SYS_USERS] ([ID], [USER_ACCOUNT], [USER_PWD], [EXPIRED_DATE], [ACTIVED], [RESERVED], [USER_TYPE], [DELETED], [CREATE_DATE], [CREATE_USER], [UPDATE_DATE], [UPDATE_USER], [FULL_NAME]) VALUES (22, N'vendor_04', N'Vrhnli5Ms52SwzYjYM6f+dEffmURRJM+76BeDIqeUTY=', NULL, 1, 0, NULL, 0, CAST(0x0000A71A00A8A88A AS DateTime), N'vendor_04', CAST(0x0000A71A00A8A88A AS DateTime), N'vendor_04', N'三星电机(深圳)有限公司')
INSERT [dbo].[SYS_USERS] ([ID], [USER_ACCOUNT], [USER_PWD], [EXPIRED_DATE], [ACTIVED], [RESERVED], [USER_TYPE], [DELETED], [CREATE_DATE], [CREATE_USER], [UPDATE_DATE], [UPDATE_USER], [FULL_NAME]) VALUES (23, N'tonyzhang', N'f1SaQCPg4apjUrDz/oxOlL8q88EAflGSh5e2iFDw3kg=', NULL, 1, 0, NULL, 0, CAST(0x0000A71B011AB118 AS DateTime), N'tonyzhang', CAST(0x0000A71B011AB118 AS DateTime), N'tonyzhang', N'弘毅科技')
INSERT [dbo].[SYS_USERS] ([ID], [USER_ACCOUNT], [USER_PWD], [EXPIRED_DATE], [ACTIVED], [RESERVED], [USER_TYPE], [DELETED], [CREATE_DATE], [CREATE_USER], [UPDATE_DATE], [UPDATE_USER], [FULL_NAME]) VALUES (24, N'test01', N'xYSO8NYU99d2pOf6vARYyTlMFPbBihe5rc6MW1GOLzw=', NULL, 1, 0, NULL, 0, CAST(0x0000A71C0103073A AS DateTime), N'test01', CAST(0x0000A71C0103073A AS DateTime), N'test01', N'钜亿科技')
SET IDENTITY_INSERT [dbo].[SYS_USERS] OFF
/****** Object:  Default [DF__SYS_USERS__ACTIV__40E497F3]    Script Date: 03/22/2017 16:58:35 ******/
ALTER TABLE [dbo].[SYS_USERS] ADD  DEFAULT ((0)) FOR [ACTIVED]
GO
/****** Object:  Default [DF__SYS_USERS__RESER__41D8BC2C]    Script Date: 03/22/2017 16:58:35 ******/
ALTER TABLE [dbo].[SYS_USERS] ADD  DEFAULT ((0)) FOR [RESERVED]
GO
/****** Object:  Default [DF__SYS_USERS__DELET__42CCE065]    Script Date: 03/22/2017 16:58:35 ******/
ALTER TABLE [dbo].[SYS_USERS] ADD  DEFAULT ((0)) FOR [DELETED]
GO
/****** Object:  Default [DF__SYS_USERS__CREAT__43C1049E]    Script Date: 03/22/2017 16:58:35 ******/
ALTER TABLE [dbo].[SYS_USERS] ADD  DEFAULT (getdate()) FOR [CREATE_DATE]
GO
